### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by TBehles** [gir489returns/Bioshock2CrashFix#1]
Hi,

sady Bioshock 2 remastered is still crashing for me. I wonder if you can figure out what the issue is here.

[crash.log](https://github.com/user-attachments/files/16600526/crash.log)

**Comment by gir489returns** [comment]
> sady Bioshock 2 remastered is still crashing for me. I wonder if you can figure out what the issue is here.

You have exhausted the memory of the game, and so it is crashing, nothing I can do about this.

**Comment by TBehles** [comment]
I reinstalled the game, applied just about every fix I could find online and it seems to be working now. Anyway, thank you for this mod.
