### ISSUE TITLE
the game closes as soon as I start my game

### ISSUE THREAD

**Issue by Katsumoto7** [gir489returns/Bioshock2CrashFix#2]
Crash in a minute
[crash.log](https://github.com/user-attachments/files/16826335/crash.log)
[d3d11.log](https://github.com/user-attachments/files/16826336/d3d11.log)
[dxgi_budget.log](https://github.com/user-attachments/files/16826337/dxgi_budget.log)
[eos.log](https://github.com/user-attachments/files/16826338/eos.log)
[game_output.log](https://github.com/user-attachments/files/16826339/game_output.log)
[modules.log](https://github.com/user-attachments/files/16826340/modules.log)
[steam_api.log](https://github.com/user-attachments/files/16826341/steam_api.log)

**Comment by gir489returns** [comment]
I don't even see Bioshock2CrashFix.dll in your module list. Where is the Bioshock2CrashFix's log?

**Comment by gir489returns** [comment]
@Katsumoto7 Did you figure out why it was missing yet?

**Comment by Katsumoto7** [comment]
I checked the files and none of them have that name Bioshock2CrashFix's log, I have this one Bioshock2CrashFix.dll

**Comment by gir489returns** [comment]
There should be a log file with the Bioshock2CrashFix.dll. [Use the release from here](https://github.com/gir489returns/Bioshock2CrashFix/releases/download/1.1/Crash.Fix.with.Logger.zip). Try it again. Make sure you see this in your SpecialK menu:

![image](https://github.com/user-attachments/assets/0eb29c05-7e43-45c7-bb80-6006eb981e2a)

**Comment by gir489returns** [comment]
> I must be doing something wrong, I am attaching a video of only 2 minutes where you can see what happens where you can see that I use the plugin as you say and that the log file you are telling me about is not in any of the folders.
> 
> https://drive.google.com/file/d/1Xq66IHkaUH3DmAj3U1k_bk6h9WGlvBRB/view?usp=sharing

I think what's happening is your Spanish version of Bioshock 2 might be coming with a different EXE and files than the one I am working with.

Would you be willing you swap to the English version to see if the issues resolve itself? If it does, we can investigate avenues to take from there. Also, is that the Steam version? Where is the Steam overlay?

**Comment by gir489returns** [comment]
User is not using the Steam version, closing as invalid.
